[[constraint]]
  branch = "master"
  name = "github.com/gogo/protobuf"

[[constraint]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[constraint]]
  branch = "master"
  name = "github.com/favadi/protoc-go-inject-tag"

[prune]
  go-tests = true
  unused-packages = true
